[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
account-creator = "FRhDvDaKRNW8GL1uYjWgFJ4MCqSL4y3AfUyEksDv56LX"
govern-token = "BwCHDfxcDL5eKZrZumUtxifVKZLXgVx3NuwKmyNapYWL"
post-creator = "6DZ3fUUrLKxFWjRzLRiM9XKnHG61qms8wPoyfhhnXD8C"
social-token = "DuHbzA7zoxXa7tVXypZPKM5tKkzkw6t7CCzABhx87B5m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/bismuth/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
